"""Human-reviewed audit decisions. Never generated from the numeric screener.

Row identifiers are one-based positions in the immutable audit baseline.
Quotations are literal substrings of the retained source bodies; validation
normalizes whitespace only. Decisions without a source stay unresolved.
"""

# city, event MM-DD, selected value, baseline publication row, exact excerpt,
# qualifier, reason (including alternatives/timing when material).
DAILY = [
    ("Kropyvnytskyi","07-22",50,271,"на неї вийшли пів сотні людей.","reported_count","OwnSuspcountatcompleted21:00action;340Telegramsubscribersnotdailyturnout."),
    ("Izmail","07-20",10,814,"Загалом до участі долучилися близько десяти людей.","approximate","Localbodyexplicit20JulyIzmail;participantoriginsKyiv/Odesadonotchangeactionlocation."),
    ("Lviv","07-21",300,253,"площа у центрі міста знову зібрала сотні небайдужих львів’ян.","normalized_hundreds","Recoveredlocal21Julyarticlecurrentbody;preservehundreds→300convention,notanexplicitheadcount."),
    ("Lutsk", "07-20", 250, 195, "орієнтовно 250 людей, розповів поліцейський Василь Климюк.", "police_estimate", "Recovered from unknown6Augbatch: local report explicitly dates march to20July and attributes count to named police officer."),
    ("Ternopil", "07-20", 200, 219, "О 20:30 було майже 200 учасників.", "near_upper_bound", "Newly recovered local20July report has explicit20:30timed almost200 observation; Ukrinform>100 is compatible lowerbound,not additive. Newcitypeak200."),
    ("Ivano-Frankivsk", "07-21", 50, 232, "Станом на початок акції зібралося приблизно 50 людей.", "approximate", "Local21July explicitdateand19:00assembly; nationalroundupcorroborates."),
    ("Mykolaiv", "07-24", 50, "4b7e0cf8ab2e4f4903f9", "До заходу долучилися понад 50 людей", "police_count", "Targeted recovery of missing local ninth-day report. Publication metadata and publisher24July archive confirm date; body attributes count to dialogue police."),
    ("Vinnytsia", "07-19", 40, "dff95351a1d57d5856ea", "Десятки людей вийшли на вулиці у Вінниці.", "normalized_dozens", "Targeted recovery found an in-cutoff fourth-day report explicitly about Vinnytsia on19July. Preserve the documented dozens→40 convention; this is normalized, not an explicit headcount."),
    ("Vinnytsia", "07-17", 300, "a97ba813b4a58112d3b4", "Увечері 17 липня на Майдані Незалежності зібралися кілька сотень людей", "normalized_several_hundred", "Targeted gap search recovered local detailed report explicitly about evening17July, published18July. Normalize several hundred300 under agreed rule; future18–19July announcements are not observations."),
    ("Khmelnytskyi", "07-20", 100, "1a01b1eb953a8c0f1225", "Близько 100 людей доєдналося до акції.", "approximate", "Targeted canonical/AMP recovery found local report explicitly dated20July. Named current on-site reporting supports baseline hundred."),
    ("Oleksandriia", "07-19", 25, "dd4619d2f52e1c53eab4", "В Олександрії о 17:00 25 людей зібралися на Соборній площі.", "organiser_count", "Local report explicitly dates first Oleksandriia protest to19July and attributes25 to co-organizer Yeva Batiashova. Distinct from Kropyvnytskyi150."),
    ("Zaporizhzhia", "08-16", None, 902, "", "disproved_city_assignment", "Original80 belongs to Ivano-Frankivsk subsection. Targeted SODA local report confirms Zaporizhzhia march16August,19:00–20:00, but gives no count. No numerical replacement can be justified."),
    ("Rivne", "08-01", None, 738, "", "disproved_event_date", "Source explicitly describes31July, published1August. Reviewed alternative31July report and targeted1August search; no independent1August count recovered. Blank is missing evidence, not zero attendance."),
    ("Rivne", "07-16", 50, 76, "Приблизно півсотні людей взяли участь в акції", "approximate", "Local body explicitly dates action to 16 July; march to fallen defender's funeral is not added as protest turnout."),
    ("Rivne", "07-21", 100, 257, "21 липня зібралися майже 100 людей", "near_upper_bound", "Explicit date at Theatre Square; national roundup corroborates."),
    ("Rivne", "07-24", 150, "654cfd8f16d2bf8c6996", "за нашими підрахунками, зібралося близько 150 людей.", "approximate", "Correct lower-bound 50 to Fourth Estate's own count explicitly dated 24 July in its retrospective local section. Suspilne's >50 does not impose an upper limit and is compatible; retain both observations."),
    ("Rivne", "07-27", 40, 489, "Понад 40 людей попри дощ зібралися 27 липня", "lower_bound", "Local current-day lead at Theatre Square; remove unrelated author/page furniture."),
    ("Rivne", "07-31", 100, 709, "Приблизно сто людей вийшли на протестну ходу", "approximate", "Local body explicitly says 31 July; 1 August Rayon report describes this same march, not a new next-day action."),
    ("Rivne", "08-08", 30, 822, "До 30 людей зібралося 8 серпня на Театральній площі у Рівному", "upper_bound", "Dated lying-down protest; ordinal day24 is not a count."),
    ("Rivne", "07-25", 60, "654cfd8f16d2bf8c6996", "прийшло близько 60 людей.", "approximate", "Fourth Estate's own observation in paragraph explicitly headed next day 25 July; recovered from retrospective report."),
    ("Rivne", "07-26", 60, "654cfd8f16d2bf8c6996", "як ми порахували, близько 60 людей.", "approximate", "Fourth Estate's own count explicitly dated 26 July; preserve as separate day, not added to 25 July."),
    ("Mykolaiv", "07-16", 45, 80, "Біля міської ради зібралися 45 людей", "reported_count", "Own local correspondent's 16 July morning action; duration 1.5 hours is not crowd size. Other 30 and roughly50 are separate approximate observations."),
    ("Mykolaiv", "07-18", 150, 131, "До заходу долучилися понад 150 людей.", "lower_bound", "Mykolaiv subsection explicitly names 18 July; not the neighboring city's count."),
    ("Mykolaiv", "07-20", 80, 210, "близько 80 людей, переважно молодь", "approximate", "Ukrinform's own correspondent describes Monday evening march; local/national Suspilne and Espreso corroborate."),
    ("Mykolaiv", "07-21", 35, 256, "До заходу долучилися 35 людей", "police_count", "Local current-day body attributes count to dialogue police inspector Alla Tkachenko."),
    ("Mykolaiv", "07-22", 30, 288, "До заходу долучилися 30 людей", "police_count", "Local current-day body attributes count to dialogue police."),
    ("Mykolaiv", "07-25", 55, 398, "У Миколаєві до акції долучилися 55 людей.", "reported_count", "Current Mykolaiv subsection of tenth-day roundup; Dnipro >50 is not the same count."),
    ("Mykolaiv", "07-26", 32, 426, "До заходу долучилися 32 людини", "police_count", "Local report names dialogue police inspector; exact body excerpt replaces image captions and page furniture."),
    ("Mykolaiv", "07-27", 35, 481, "До акції в Миколаєві долучилися близько 35 людей.", "approximate", "Local 12th-day body, corroborated by national roundup."),
    ("Mykolaiv", "07-28", 25, 528, "У Миколаєві 28 липня близько 25 людей зібралися", "approximate", "Explicit city/date in Oboz, corroborated by national Suspilne."),
    ("Mykolaiv", "08-03", 12, 772, "у Миколаєві близько 12 людей зібралися біля міської ради.", "approximate", "NV current-day body explicitly relays Suspilne; neighboring Lviv hundred not merged."),
    ("Chernivtsi", "07-16", 40, 86, "у Чернівцях кілька десятків людей вийшли на Центральну площу", "normalized_several_dozen", "Preserve baseline several-dozen → 40 convention; explicitly normalized, not a counted 40."),
    ("Chernivtsi", "07-17", 30, 123, "На Центральній площі у Чернівцях близько 30 людей", "approximate", "Current Chernivtsi subsection in second-day roundup."),
    ("Chernivtsi", "07-31", 150, 611, "У Чернівцях приблизно 150 активісти пройшлися", "approximate", "Molbuk body (including its original grammatical form) reports completed march. Peak link must use this working article rather than stale unrelated URL."),
    ("Zhytomyr", "07-16", 30, 92, "прийшли близько 30 людей.", "approximate", "Local body attributes current morning observation to named correspondent Mariia Kravchuk."),
    ("Zhytomyr", "07-20", 70, 227, "Станом на 21:00 акція продовжувалася — до неї долучилися близько 70 житомирян.", "approximate", "Later 21:00 update versus ~50 at 19:00 assembly in same article. Working publication URL replaces stale city-summary link."),
    ("Zhytomyr", "07-21", 30, 262, "зібралися близько 30 людей", "approximate", "Own reporter's beginning-of-action observation explicitly dated 21 July. Later arrivals unquantified; do not invent an updated number."),
    ("Sumy", "07-16", 20, 110, "стоять до двадцяти людей.", "upper_bound", "Tsukr own report explicitly dates Sadko fountain gathering to morning16July."),
    ("Sumy", "07-17", 20, 124, "на мирну акцію вийшли близько двох десятків людей.", "approximate", "Sumy subsection of second-day roundup; no inference from border-security discussion."),
    ("Kolomyia", "07-16", 11, 111, "Вранці 16 липня 11 молодих людей зібралися під ратушею", "reported_count", "Local Informator body explicitly names city/date; neighboring Ivano-Frankivsk dozens are separate."),
    ("Chernihiv", "07-20", 150, 154, "понад півтори сотні людей зібралися на акцію", "lower_bound", "Local body explicitly dates action to evening20July, Red Square; recover working article instead of stale city-summary URL."),
    ("Kalush", "07-20", 50, 167, "У Калуші понад 50 людей", "lower_bound", "20 July local regional roundup has a distinct Kalush section; neighboring Kolomyia40 is not part of Kalush turnout."),
    ("Kolomyia", "07-20", 40, "18979c7a1d730284ba22", "Орієнтовно 40 людей вийшли на площу Відродження", "approximate", "Overlooked current Kolomyia section of 20 July regional article, explicitly separate from Kalush50."),
    ("Khmelnytskyi", "07-24", 30, "4f6a7d023a04b078d3af", "Понад 30 людей зібралось у середмісті Хмельницького", "lower_bound", "Targeted recovery of missing local Suspilne report, explicitly dated 24 July."),
    ("Poltava", "07-31", 100, 706, "о 19:00 зібралося понад сотню", "lower_bound", "Local body explicitly says 31 July, then describes march; original rewritten quote replaced by literal excerpt."),
    ("Zaporizhzhia", "07-16", 60, 66, "Близько 60 місцевих жителів вийшли з плакатами", "approximate", "Explicit 16 July local report; 061 own correspondent's >50 is compatible."),
    ("Kropyvnytskyi", "07-16", 60, 94, "було 30 людей, о 9:30 — 60.", "reported_count", "Own reporter observed growth from 30 at start to 60 at 09:30; observations are not summed."),
    ("Kropyvnytskyi", "07-17", 90, 119, "о 10:00 — майже сотня людей.", "normalized_almost_hundred", "Preserve baseline 90 normalization of almost a hundred, explicitly flagged as non-exact. Earlier 09:19 assembly was 30."),
    ("Kropyvnytskyi", "07-19", 150, "dd4619d2f52e1c53eab4", "до акції долучилися півтори сотні людей.", "organiser_estimate", "Local 19 July article names co-organizer Denys Markov; separate Oleksandriia subsection is not part of this city count."),
    ("Kropyvnytskyi", "07-20", 66, 174, "участь в акції взяли 66 людей.", "police_count", "Local report attributes explicit 66 to security police; action lasted two hours, not 66 actions."),
    ("Kropyvnytskyi", "07-26", 30, 416, "зібралися понад три десятки людей.", "lower_bound", "Grechka explicitly dates current event to 26 July; participant's general stable ~30 comment corroborates but does not substitute for dated observation."),
    ("Uzhhorod", "07-16", 50, 75, "на протест зібралися близько 50 людей.", "police_estimate", "Local report names regional police spokesperson Kateryna Petrunio."),
    ("Uzhhorod", "07-30", 20, 607, "В Ужгороді участь у мітингу взяли близько 20 осіб.", "approximate", "Current 30 July roundup; NV corroborates local Suspilne observation."),
    ("Uzhhorod", "08-05", 12, 808, "Станом на 20:00 на площі 12 людей.", "snapshot_count", "Explicit 20:00 snapshot retained; participants' >30 with continual turnover is not a simultaneous count and is recorded separately."),
    ("Uzhhorod", "08-07", 20, 815, "Станом на 20:25 зібралося 20 людей", "snapshot_count", "Local article explicitly says 7 August, followed by march; Oboz corroborates."),
    ("Uzhhorod", "08-08", 12, 823, "8 серпня станом на 20:30 на мітинг прийшли дванадцятеро людей.", "snapshot_count", "Explicit date and time in local body; spelled-out twelve is an explicit number."),
    ("Uzhhorod", "08-09", 12, 826, "9 серпня станом на 20:40 на мітинг прийшли 12 людей.", "snapshot_count", "Explicit date/time in local body."),
    ("Uzhhorod", "08-10", 17, 827, "10 серпня станом на 20:30 на мітинг прийшли 17 людей.", "snapshot_count", "Explicit body observation time retained despite earlier article creation time; no inference from latest page modification."),
    ("Uzhhorod", "08-11", 15, 828, "Станом на 20:30 на площі Поштовій було 15 людей.", "snapshot_count", "Current 11 August local report; participant count is distinct from 27th protest-day label."),
    ("Uzhhorod", "08-12", 9, 829, "Станом на 20:20 на площі Поштовій було 9 людей.", "snapshot_count", "Local opening paragraph explicitly dates event to 12 August."),
    ("Kharkiv", "08-07", 100, "8c1784a3b2751d3b13f4", "У Харкові на майдан Свободи 7 серпня знову вийшли до сотні людей", "upper_bound", "Overlooked current-event count in 7 August Oboz roundup; add separately from Dnipro/Uzhhorod numbers."),
    ("Ivano-Frankivsk", "07-31", 120, "afeed7ed28164c1f6ec1", "Увечері 31 липня тут зібралися орієнтовно 120 людей.", "approximate", "Overlooked current-event count in Ivano-Frankivsk subsection; not the Dnipro assembly count in the same roundup."),
    ("Kyiv", "08-16", 1500, 907, "16 серпня взяли участь до 1,5 тис. мітингувальників.", "upper_bound_contested", "Explicit retrospective event date in an in-cutoff 18 August report supports the retained upper bound. Suspilne's contemporaneous assembly estimate is ~1,000; retain it as an alternative, without treating either figure as exact."),
    ("Kharkiv", "07-30", 50, "93bd9dc86a121848515b", "У Харкові на акцію зібралося близько півсотні людей", "approximate", "Recovered NV body explicitly says 30 July. Source already represented for other cities, but missing Kharkiv publication×city record needs a 3 Sep addition."),
    ("Lviv", "08-05", 150, 802, "долучилися близько півтора сотні людей.", "approximate", "Novyny.LIVE explicitly describes Wednesday 5 August; publication at 00:24 on 6 August is not the event date."),
    ("Odesa", "08-16", None, 901, "", "disproved_city_assignment", "Original 50 quotation belongs to the Mykolaiv subsection, not Odesa. Odesa action is confirmed but no number recovered after source/context review and targeted search. Blank canonical count, retain original 50 in baseline."),
    ("Mykolaiv", "08-16", 50, "1d165874ef6d3ac03f61", "Загалом до протесту долучилися понад 50 людей.", "lower_bound", "Recovered count belongs to the Mykolaiv march from city sign via Soborna to city council; previously misassigned to Odesa."),
    ("Ivano-Frankivsk", "08-16", 80, "89c95e65b6615ab6066a", "Участь у заході взяли орієнтовно 80 людей.", "approximate", "Explicit evening 16 August Ivano-Frankivsk subsection; not the Zaporizhzhia count in the adjacent city material."),
    ("Ternopil", "07-16", 100, 48, "на акцію прийшло майже 100 людей.", "near_upper_bound", "Local correspondent's morning action; eight remaining at 17:45 is a later snapshot, not the daily peak."),
    ("Ternopil", "07-17", 20, 120, "Зібралося близько двох десятків людей.", "approximate", "Current Ternopil subsection of second-day national report."),
    ("Ternopil", "07-18", 50, 132, "понад 50 учасників акції", "lower_bound", "Ternopil subsection explicitly gives 19:00 observation on 18 July."),
    ("Ternopil", "07-31", 100, 711, "Понад сто людей пройшли", "lower_bound", "Local report explicitly dates completed march to 31 July; national dozens may describe earlier assembly."),
    ("Khmelnytskyi", "07-16", 100, 59, "участь в мітингу беруть близько сотні людей.", "approximate", "Vsim own reporter's 09:20 count, corroborated by Ye's own correspondent."),
    ("Khmelnytskyi", "07-18", 150, 136, "зібралися понад 150 людей.", "lower_bound", "Explicit 20:15 observation on 18 July; original city summary's 16 July hundred is not the period peak."),
    ("Lutsk", "07-16", 100, 53, "близько сотні містян вийшли на протест", "approximate", "Body explicitly says Lutsk 16 July; source's Rivne subsection is a separate city."),
    ("Lutsk", "07-17", 50, 117, "долучилися орієнтовно пів сотні людей.", "approximate", "Explicit morning action in Lutsk subsection; not inferred from article's citywide headline."),
    ("Lutsk", "07-19", 300, 147, "зібралися понад 300 людей.", "lower_bound", "Fourth-day Lutsk evening subsection; summary must reconcile to this peak rather than first-day hundred."),
    ("Lutsk", "07-24", 100, 359, "долучилася орієнтовно сотня людей", "organiser_estimate", "Local report names co-organizer Anton Svatko and observation time 19:45."),
    ("Lutsk", "07-26", 60, 423, "станом на 20:30 доєдналося понад 60 людей", "lower_bound", "Local correspondent observation explicitly dated 26 July."),
    ("Cherkasy", "07-16", 100, 62, "На зібранні присутні близько сотні містян", "approximate_contested", "Suspilne own observation ~100; Dzvin's ~30 is another observation near the beginning, with no reliable synchronized count to reconcile them."),
    ("Cherkasy", "07-18", 100, 135, "Більше сотні людей", "lower_bound", "National report's Cherkasy subsection explicitly names 18 July."),
    ("Cherkasy", "07-19", 150, 148, "150 людей вийшли на акцію в Черкасах.", "reported_count", "Fourth-day Cherkasy subsection, not the nearby Dnipro 150 count."),
    ("Cherkasy", "07-20", 150, 152, "вийшли понад 150 містян.", "lower_bound", "Current-day Cherkasy subsection; Espreso relays same count."),
    ("Cherkasy", "07-24", 150, 322, "Близько 150 людей вийшли на Соборну площу у Черкасах.", "approximate", "Local report describes resumed action after three-day break; background 18 July >100 is not current turnout."),
    ("Cherkasy", "07-25", 80, 374, "У Черкасах близько 80 людей вийшли на Соборну площу", "approximate", "Local current-event lead; remove author surname from stored quote. Other article's adjacent Dnipro >50 is unrelated to this city."),
    ("Vinnytsia", "07-16", 120, 98, "участь у заході взяли майже 120 людей.", "near_upper_bound", "Dialogue police count in local Suspilne article, explicitly dated 16 July."),
    ("Poltava", "07-16", 100, 74, "на акцію протесту прийшло близько сотні людей.", "approximate_contested", "Suspilne own count retained; Poltavshchyna's ~70 remains a separate observation. No addition or claim of exact census."),
    ("Poltava", "07-17", 20, 121, "Близько 20 людей скандують", "approximate", "Poltava subsection of second-day current-event report."),
    ("Poltava", "07-20", 130, 217, "Близько 130 учасників із плакатами", "approximate", "Current fifth-day lead, not the retrospective first-day ~100 paragraph in the same article."),
    ("Poltava", "07-24", 80, 364, "зібралося майже вісім десятків людей.", "near_upper_bound", "National Poltava subsection explicitly says 24 July; neighboring Rivne 50 is a separate count."),
    ("Lviv", "07-16", 300, 33, "декілька сотень львів’ян зібралися на акцію", "normalized_several_hundred", "ZAXID body explicitly says Thursday 16 July; preserve several-hundred → 300 convention, not an explicit count."),
    ("Lviv", "07-27", 150, 476, "вийшли близько 150 людей", "police_estimate", "UP's Lviv clause attributes the figure to police; local Suspilne corroborates, unlike undated/earlier hundred descriptions."),
    ("Lviv", "07-28", 200, 525, "У Львові біля пам'ятника Тарасові Шевченку зібралися близько 200 людей.", "approximate_contested", "Retain current-day Suspilne ~200. UP's ~150 is a competing observation and is not silently discarded."),
    ("Lviv", "07-30", 200, 606, "зібралося близько 200 людей.", "police_estimate", "Dated 30 July report cites law enforcement at Shevchenko monument; Oboz corroborates."),
    ("Lviv", "07-31", 300, 693, "У Львові кілька сотень людей зібралися", "normalized_several_hundred", "31 July march from Shevchenko monument to Rynok Square; preserve several-hundred → 300 convention."),
    ("Lviv", "08-03", 100, 771, "У Львові на акцію вийшли близько сотні людей.", "approximate", "NV current-event paragraph; adjoining Mykolaiv 12 is a separate city's observation."),
    ("Odesa", "07-16", 100, 39, "на неї прийшли понад сто людей.", "lower_bound_contested", "Correct arbitrary 150 to the explicitly supported lower bound 100. Local Suspilne distinguishes 09:00–11:00 action from 13:30 regathering (>60); do not add them. Dumskaya says hundreds without a precise number."),
    ("Odesa", "07-19", 1000, 146, "близько тисячі людей.", "approximate", "Odesa subsection of fourth-day roundup; 24 Kanal attributes reporting to Suspilne. Approximate boundary is not itself evidence of source disagreement."),
    ("Odesa", "07-20", 150, 211, "зібралися понад 150 людей.", "lower_bound", "Local Suspilne fifth-day report; Espreso corroborates the same attributed observation."),
    ("Odesa", "07-25", 40, 399, "в Одесі, де сьогодні зібралися кілька десятків протестувальників.", "normalized_several_dozen", "Preserve existing several-dozen → 40 convention and flag it as normalized, not an explicit count."),
    ("Odesa", "07-31", 200, 703, "До неї долучилися близько 200 людей.", "approximate", "Local report explicitly dates march to 31 July, Deribasivska to Duke monument."),
    ("Ivano-Frankivsk", "07-16", 200, "1ab5725874961ff73edc", "до акції долучилися орієнтовно 200 людей.", "police_estimate", "Named regional police spokesperson; correspondent also gives about two hundred. Early dozens, >100 and relay ~300 are separate observations, not summed."),
    ("Ivano-Frankivsk", "07-18", 200, 138, "орієнтовно 200 людей", "approximate", "City subsection explicitly says 18 July 2026, third day; no estimate inferred from ordinal day."),
    ("Ivano-Frankivsk", "07-19", 250, 142, "прийшли приблизно 250 людей.", "approximate", "City subsection explicitly dates assembly at oblast administration to evening 19 July; correct city peak must reconcile to this value."),
    ("Ivano-Frankivsk", "07-26", 50, 410, "на площі зібралися приблизно пів сотні людей.", "approximate", "Current body explicitly says 26 July around 19:00; baseline's 200 quote was a related-news headline about 1 August."),
    ("Ivano-Frankivsk", "07-27", 50, 442, "прийшли приблизно 50 містян.", "approximate", "Censor current-day city clause, corroborated by national roundup."),
    ("Ivano-Frankivsk", "07-28", 100, 500, "прийшли майже 100 містян", "near_upper_bound", "Explicit 28 July body; replace unrelated 1 August headline in original quotation."),
    ("Ivano-Frankivsk", "07-29", 50, 547, "прийшли майже 50 містян", "near_upper_bound", "Explicit 29 July body; replace unrelated 1 August headline in original quotation."),
    ("Ivano-Frankivsk", "07-30", 60, 592, "прийшли орієнтовно 60 містян.", "approximate", "Explicit 30 July body; replace unrelated 1 August headline in original quotation."),
    ("Ivano-Frankivsk", "08-01", 200, 721, "прийшли орієнтовно 200 учасників", "approximate", "Explicit 1 August assembly before 20:00 march; remove UI furniture from quote."),
    ("Ivano-Frankivsk", "08-08", 100, 824, "У ході взяли участь орієнтовно 100 людей.", "approximate", "Explicit 8 August march, beginning 20:20; background photos from 1 August do not change event date."),
    ("Dnipro", "07-25", 50, 376, "До акції протесту долучилося понад 50 людей", "lower_bound", "Local tenth-day action, initial assembly; no supported later higher count in the article."),
    ("Dnipro", "07-26", 30, 407, "Близько 30 учасників розгорнули прапор України", "approximate", "Local eleventh-day report; national roundup corroborates."),
    ("Dnipro", "07-28", 100, 495, "У Дніпрі до мітингу долучилось близько ста людей.", "approximate", "Article explicitly identifies Tuesday 28 July; national Suspilne corroborates."),
    ("Dnipro", "07-29", 100, 545, "29 липня, на 14-й день, до мітингу долучилось близько ста людей.", "approximate_contested", "Correct 80 to the local correspondent's explicit current-event estimate of ~100. Censor/Oboz relay ~80 from Suspilne; preserve that conflicting observation, do not infer why the body differs or treat modification time as evidence."),
    ("Dnipro", "07-31", 500, 618, "Загалом до акції долучилися близько пів тисячі людей.", "approximate", "Full body distinguishes ~100 at assembly from ~500 during the completed march. Retain the latter for daily turnout."),
    ("Dnipro", "08-02", 20, 741, "У Дніпрі близько 20 людей долучилися до 19-ї акції", "approximate_contested", "Preserve detailed Dnipro.media own-correspondent observation (published 2 August 17:16 UTC). Suspilne reports ~50 the same day; timing cannot reconcile them, so both remain and the lower selected value is explicitly contested."),
    ("Dnipro", "08-04", 50, 776, "У Дніпрі близько 50 містян долучилися до акції підтримки", "approximate", "Censor explicitly relays Suspilne in a 4 August current-event roundup."),
    ("Dnipro", "08-05", 50, 810, "прийшли близько 50 людей.", "approximate", "Detailed Dnipro.media body explicitly dates the silent 22nd action to 5 August despite next-day publication. NV's 'Wednesday 6 August' conflicts with weekday/21st-day labels; not used to move this event."),
    ("Dnipro", "08-06", 30, 830, "У Дніпрі близько 30 людей долучилися до 23-ї акції", "approximate", "Body explicitly says 6 August, new location at city council. The previous OVA silent action is 5 August, not an additional 6 August count."),
    ("Dnipro", "08-07", 35, 831, "У Дніпрі близько 35 людей долучилися до 24-ї акції", "approximate_contested", "Detailed primary report explicitly dates the city-council action to 7 August. Preserve own reporter's ~35; roundup's ~40 remains a separate approximate observation."),
    ("Dnipro", "08-09", 25, 833, "Близько 25 людей зібралися біля будівлі Дніпровської міської ради", "approximate", "Current-event local report of 26th action; publication date supplies date where body does not explicitly repeat it."),
    ("Dnipro", "08-10", 35, 834, "У Дніпрі близько 35 людей взяли участь у 27-й акції", "approximate", "Current-event local report; announced later march is not evidence it happened on 10 August."),
    ("Dnipro", "08-11", 50, 835, "У Дніпрі 11 серпня близько 50 людей долучилися до мітингу.", "approximate", "Explicit event date in local report; Shelter's Kyiv 31 July retrospective does not measure Dnipro turnout."),
    ("Dnipro", "08-12", 30, 836, "На захід зібралися близько 30 людей.", "approximate", "Opening paragraph explicitly dates the OVA action to 12 August."),
    ("Dnipro", "08-14", 30, 837, "На захід зібралися близько 30 людей.", "approximate", "Opening paragraph explicitly dates the city-council action to 14 August."),
    ("Dnipro", "08-15", 20, 838, "На неї увечері 15 серпня 2026 року прийшли близько 20 людей.", "approximate", "Explicit date; separate from the 16 August march announced later in the article."),
    ("Dnipro", "08-16", 100, 839, "загалом участь у заході взяли близько 100 протестувальників.", "approximate", "March's total observed participation after others joined; national Suspilne independently corroborates ~100."),
    ("Dnipro", "08-17", 20, 840, "Цього разу на 34-й протест прийшли понад 20 людей.", "lower_bound", "Opening paragraph explicitly names evening 17 August."),
    ("Dnipro", "08-18", 30, 841, "На акцію прийшли близько 30 людей.", "approximate", "Opening paragraph explicitly names evening 18 August and city council."),
    ("Dnipro", "08-19", 35, 842, "На мітинг прийшли близько 35 людей.", "approximate", "Farewell daily-format gathering on 19 August; movement's later return is not excluded."),
    ("Dnipro", "08-29", 15, 843, "На захід зібралися близько 15 людей.", "approximate", "Opening paragraph explicitly says 29 August at Dnipro city council; publication remains within cutoff."),
    ("Kyiv", "07-23", 300, 311, "У Києві зібралося кілька сотень людей", "normalized_several_hundred", "Correct 500 to the agreed several-hundred normalization. LB's 500 was published at 00:04 on 23 July but links the seventh-day Suspilne report about 22 July; it is not 23 July evidence. Radio Svoboda observed about 100 at 20:00."),
    ("Kyiv", "07-26", 150, 421, "на акцію вийшло близько 150 людей.", "approximate", "National Suspilne Kyiv section, assembly from 19:00. Local Lviv/Uzhhorod/Khmelnytskyi articles incorrectly attached to Kyiv do not substantiate this count."),
    ("Kyiv", "07-27", 300, 453, "акція біля театру імені Івана Франка зібрала кількасот людей", "normalized_several_hundred", "Correct arbitrary 200 to documented several-hundred → 300 convention. Liga relays Interfax and warns of participant turnover; no exact headcount is claimed. Ignore interview's undated 4–6k-per-day generalization."),
    ("Kyiv", "08-01", 100, 729, "у столиці на антиурядовий виступ зібралися понад 100 осіб.", "lower_bound", "Lead explicitly names 1 August; retain lower bound. The same article includes retrospective march/organizer background, which is not a second current count."),
    ("Kyiv", "08-04", 120, 782, "відбувся мітинг за участю близько ста двадцяти людей.", "approximate", "Direct Novyny.LIVE report; correspondent relay's 100–120 interval is compatible, not additional participants."),
    ("Kyiv", "08-14", 300, 887, "Близько трьох сотень людей відгукнулися на заклик", "approximate_contested", "DW's observation of about 300 retained against earlier Suspilne <=100 and other larger claims; source/time differences remain flagged, not resolved by selecting the largest."),
    ("Kharkiv", "07-16", 300, 17, "за пів години їх побільшало орієнтовно до 300.", "approximate", "MediaPort correspondent: morning 09:00 assembly about 100 grows to about 300 after half an hour. Evening action of <=50 is separate."),
    ("Kharkiv", "07-20", 350, "0cddb7f8c079966fc27b", "Станом на 20:00 на акції зафіксували близько 350 людей", "police_estimate", "Targeted recovery of missing local Suspilne article; explicit 20 July and police spokesperson attribution."),
    ("Dnipro", "07-16", 300, 26, "На протест зібралися близько 300 людей, їхня кількість збільшується.", "approximate", "Morning gathering in local correspondent report; evening continuation is separately described with no additional count."),
    ("Kyiv", "07-16", 2000, 1, "захід зібрав близько двох тисяч учасників.", "approximate", "Interfax correspondent's assembly estimate; other reporters observed 1,000–1,400 and earlier hundreds. These are different observations, not an additive total."),
    ("Kyiv", "07-17", 3000, 115, "На площі перебувають близько 3 тисяч людей.", "approximate", "Evening square turnout; morning gathering of about 200 is a separate observation."),
    ("Kyiv", "07-18", 2000, 128, "Станом на 21:45 у Києві зібралось на протесті близько 2 тисяч людей", "approximate", "Later 21:45 update supersedes this article's 19:30 assembly count of about 300."),
    ("Kyiv", "07-19", 5000, 140, "зібралося понад 5000 людей", "lower_bound", "Liga attributes the estimate to Interfax; retain the stated lower bound, not an exact headcount."),
    ("Kyiv", "07-20", 300, 181, "На площі Франка у столиці вкотре зібралися сотні киян.", "normalized_hundreds", "Current-event paragraph, not the article's retrospective first-day paragraph. Preserve baseline convention: hundreds → 300."),
    ("Kyiv", "07-21", 300, 251, "у Києві на протест зібралося кілька сотень людей.", "normalized_several_hundred", "Ukrinform relays Suspilne. Preserve documented several-hundred → 300 convention."),
    ("Kyiv", "07-22", 500, 281, "У Києві зібралося близько 500 людей", "approximate", "Suspilne correspondent's current-event count."),
    ("Kyiv", "07-31", 6000, 684, "Поліція каже про 6 тисяч учасників.", "police_estimate", "Select the police estimate of the completed march. The organiser's up-to15000 claim is retained as a competing source estimate; early approximately1000 assembly and vague thousands are different observations, not additive totals. Neither the largest number nor page modification time determines selection."),
    ("Kyiv", "08-03", 200, 765, "Близько 200 мітингувальників зібрала у Києві у понеділок, 3 серпня, чергова акція протесту", "approximate", "DW body explicitly names both city and event date."),
    ("Kyiv", "08-18", 30, 907, "перебувало не більше трьох десятків мітингувальників.", "upper_bound", "Obozrevatel relays Interfax; another observation of about 20 is retained separately, not summed."),
    ("Kyiv", "08-19", 100, 910, "на акції протесту були присутні близько сотні людей.", "approximate", "Parliament-area daytime action; evening gathering of about 30 is a different action. Graty corroborates daytime hundred."),
    ("Kharkiv", "07-18", 400, 139, "близько 400 людей", "police_estimate", "Article's Kharkiv subsection explicitly gives police estimate at 20:00, 18 July."),
    ("Kharkiv", "07-19", 450, 141, "Кількість учасників акції станом на 20:30 склала 450 людей.", "reported_count", "Kharkiv subsection's later 20:30 observation, following an earlier over-400 figure."),
    ("Kharkiv", "07-24", 250, 332, "250 людей", "approximate", "Local Suspilne article explicitly dates the action to 24 July; national roundup corroborates."),
    ("Kharkiv", "07-25", 150, 380, "до 150 людей", "upper_bound", "Local Suspilne reports police spokesperson's 20:00 upper bound."),
    ("Kharkiv", "07-26", 180, 412, "180 людей", "approximate", "Local report explicitly identifies the event as 26 July."),
    ("Kharkiv", "07-28", 90, 502, "90 людей", "police_estimate", "Roundup explicitly places Kharkiv police estimate on 28 July; local article's ordinal day label is inconsistent, so not used to infer the date."),
    ("Dnipro", "07-17", 300, 126, "Загалом в місті зібралося близько 300 людей.", "approximate", "Current Dnipro subsection of the second-day roundup."),
    ("Cherkasy", "08-18", 30, 904, "За його підрахунками, на площі зібралося 30 людей.", "organiser_estimate", "Current18August action; the article attributes the estimate to organiser Ihor Bobyriev. Legislative vote numbers are not turnout."),
    ("Chernivtsi", "07-20", 100, 158, "Увечері 20 липня близько сотні чернівчан прийшли на Центральну площу із картонками.", "approximate_contested", "Later evening observation from Ukrinform's local correspondent replaces the earlier several-dozen snapshot. Preserve the local Suspilne normalization40 as a compatible earlier alternative."),
    ("Dnipro", "07-19", 200, 159, "Близько 200 людей зібралися 19 липня", "approximate_contested", "Local Dnipro.media current-event report is the more specific completed gathering; national150 remains a documented alternative and is not added."),
    ("Dnipro", "07-20", 300, 228, "У Дніпрі 20 липня близько 300 людей зібралися", "approximate_contested", "Local Dnipro.media current-event report replaces the earlier national-roundup estimate100 for the same action; retain100 as an earlier alternative."),
    ("Dnipro", "07-27", 50, 494, "Близько 50 людей зібралися 27 липня", "approximate_contested", "Select the local publisher's own current-event observation over the national relay's80; retain80 as a contested alternative."),
    ("Dnipro", "07-30", 70, 588, "30 липня до мітингу долучилось близько 70 людей.", "approximate", "Local current-day report; an independent same-day local article repeats approximately70."),
    ("Ivano-Frankivsk", "07-23", 70, 297, "Станом на 19:30 на акцію прийшли орієнтовно 70 мітингувальників.", "approximate", "Local report gives an explicit19:30 snapshot on23July; no Kolomyia action is described."),
    ("Ivano-Frankivsk", "07-24", 100, 327, "Участь у мітингу бере майже сотня людей.", "near_upper_bound", "Local24July report supports almost100; store100 with its non-exact qualifier rather than treating it as an exact count."),
    ("Ivano-Frankivsk", "08-02", 40, 743, "прийшли понад 40 учасників", "lower_bound", "Current2August local report gives a strict lower bound; a retrospective relay corroborates it. Do not convert >40 into an exact headcount."),
    ("Ivano-Frankivsk", "08-03", 30, 761, "зібралися 30 учасників", "reported_count", "Current3August local report; neighboring page furniture and protest-day ordinals are excluded."),
    ("Ivano-Frankivsk", "08-14", 100, 891, "Участь у заході взяли орієнтовно 100 людей", "approximate", "Current14August Ivano-Frankivsk subsection contains an explicit approximate count."),
    ("Ivano-Frankivsk", "08-19", 30, 912, "У ньому беруть участь, за підрахунками поліцейських, 30 людей.", "police_morning", "Morning19August police snapshot; the later evening action is separately documented without a number and is not added."),
    ("Kharkiv", "07-31", 150, 628, "до акції доєдналися до 150 учасників.", "upper_bound", "Local31July report preserves the police upper bound; it is not an exact150 headcount."),
    ("Khmelnytskyi", "07-25", 40, 381, "Станом на 19:15 там було 40 осіб.", "snapshot_count", "Local current-day report gives an explicit19:15 observation."),
    ("Kremenchuk", "07-24", 40, 337, "Цього разу на мітинг зібралося кілька десятків людей.", "normalized_several_dozen", "Preserve the documented several-dozen→40 convention and flag it as normalized."),
    ("Kremenchuk", "07-31", 10, 632, "На мітинг вийшли понад десять людей.", "lower_bound", "Current31July local report supports only a strict lower bound; store10 with qualifier."),
    ("Kropyvnytskyi", "07-24", 40, 340, "Кілька десятків учасників вимагають повернути його на посаду.", "normalized_several_dozen", "Preserve several-dozen→40 normalization; not an explicit headcount."),
    ("Kropyvnytskyi", "07-25", 20, 385, "станом на початок мітингу на площі зібралися близько 20 людей", "organiser_estimate", "Current25July initial snapshot attributed to organiser Kateryna Koltunova; later arrivals are unquantified."),
    ("Kropyvnytskyi", "07-28", 20, 554, "зібралися близько двох десятків людей", "approximate", "Local report explicitly dates the action to28July; first-day retrospective counts are excluded."),
    ("Kyiv", "07-24", 1000, 354, "станом на 21:00 на площі зібралося від тисячі людей.", "lower_bound_updated", "Use Radio Svoboda's later21:00 observation for the same gathering instead of the20:00 approximately500 snapshot. Preserve both observations and do not interpret the lower bound as exact."),
    ("Kyiv", "07-25", 500, 395, "За оцінками нашого кореспондента їх було понад 500.", "lower_bound", "Direct current-event correspondent estimate after the initial <=100 assembly; retain both timed observations without summing."),
    ("Kyiv", "07-28", 300, 510, "На акцію зібралися кілька сотень учасників", "normalized_several_hundred", "Preserve several-hundred→300 convention and flag the quantity as normalized."),
    ("Lutsk", "07-31", 100, 734, "Близько сотні людей увечері 31 липня зібралися на Театральному майдані в Луцьку", "approximate", "Retrospective publication explicitly dates the Lutsk action to31July."),
    ("Lviv", "07-25", 250, 397, "На пікет прийшло близько 250 людей.", "approximate", "Current25July Lviv subsection gives an explicit approximate count."),
    ("Mykolaiv", "07-31", 17, 701, "До заходу долучилися 17 людей, повідомили в поліції діалогу.", "police_count", "Current31July local report attributes the explicit count to dialogue police."),
    ("Mykolaiv", "08-04", 9, 783, "До мирної акції долучилися дев’ятеро людей.", "reported_count", "Current4August local article contains a spelled-out explicit count; protest-day ordinal is excluded."),
    ("Rivne", "07-28", 50, 579, "цього разу на акцію прийшло близько 50 людей.", "approximate_contested", "Select the detailed local next-day report's approximately50 over the national roundup's approximately30; retain30 as a contested alternative."),
    ("Ternopil", "07-23", 100, 320, "За годину кількість мітингувальників зросла до приблизно ста людей.", "approximate_updated", "Use the later one-hour observation from the same current article, not the smaller initial assembly."),
    ("Ternopil", "07-25", 60, 400, "Близько 60 людей долучились до акції станом на 20 годину у суботу, 25 липня.", "snapshot_count", "Current25July local20:00 observation."),
    ("Uzhhorod", "07-25", 35, 402, "цього разу — близько 35.", "organiser_estimate_contested", "Select the organiser's later same-action estimate35 over the reporter's approximately25; retain both observations."),
    ("Uzhhorod", "07-26", 30, 427, "До акції протесту долучилося близько 30 людей, повідомив кореспондент Суспільного.", "approximate", "Current26July correspondent observation."),
    ("Uzhhorod", "07-29", 20, 580, "прийшли майже 20 містян", "near_upper_bound", "Current29July local report; preserve the almost qualification."),
    ("Uzhhorod", "07-31", 40, 713, "Нині до неї долучилися близько 40 людей.", "approximate", "Current31July local report."),
    ("Uzhhorod", "08-01", 20, 740, "Нині до мітингу долучилися майже 20 людей.", "near_upper_bound", "Current1August local report; preserve the almost qualification."),
    ("Uzhhorod", "08-02", 17, 757, "Наразі зібралося близько 17 учасників, люди ще підходять на мітинг.", "approximate_initial", "Current2August initial snapshot; later arrivals are unquantified."),
    ("Zhytomyr", "07-28", 2, 539, "на початку восьмої години вечора на акцію вийшли двоє людей", "initial_count", "Only verified numeric observation is the initial two-person snapshot; later arrivals are reported but unquantified, so this is not claimed as a final peak."),
    ("Kropyvnytskyi", "07-29", 10, 555, "о 19:40 участь в акції взяли близько 10 людей.", "approximate_snapshot", "Current29July local correspondent observation; the separate16July approximately50 paragraph is retrospective."),
    ("Ivano-Frankivsk", "07-22", 150, 267, "Станом на початок акції зібралося приблизно 150 людей.", "approximate_initial", "Explicit22July local19:00 assembly snapshot; related-news200 belongs to1August, not this action."),
    ("Ivano-Frankivsk", "07-25", 100, 379, "На акцію зібралася понад сотня людей.", "lower_bound", "Explicit25July local action; participant origins in Dnipro and earlier Lviv attendance are not same-day city counts."),
    ("Dnipro", "07-24", 100, 325, "До мітингу долучились близько ста людей", "approximate", "Local24July report attributes the current ninth-day observation to its correspondents."),
    ("Zhytomyr", "07-24", 50, 371, "На майдані Корольова надвечір зібралося близько 50 людей", "approximate", "Local body explicitly says evening24July and credits its correspondent; fourth-year family separation is not a headcount."),
    ("Ternopil", "07-21", 100, "7b1a55582f6269e6d2ff", "Біля стін будівлі обласної ради та ОВА зібралося близько сотні людей.", "approximate", "Ukrinform current21July Ternopil subsection; no Ternopil publication×city row existed for this source, so add audit-run evidence."),
    ("Ivano-Frankivsk", "08-07", 20, "8c1784a3b2751d3b13f4", "цього разу на акцію зібралися понад 20 учасників.", "lower_bound", "Explicit7August Ivano-Frankivsk subsection; neighboring Dnipro40 and Kharkiv100 belong to different cities."),
    ("Mykolaiv", "08-05", 8, 804, "До заходу долучилися восьмеро людей.", "reported_count_contested", "Local Suspilne current5August body gives eight; NV relay gives seven. Prefer the primary report while preserving the conflicting relay, not a sum or an automatic largest-number rule."),
]

RECOVERED_EVIDENCE = [
    ("Mykolaiv", "08-05", 7, "87260944ee9d63de394b", "До заходу долучилися семеро людей.", "relay_contested", "NV5August current Mykolaiv subsection gives seven, conflicting with primary Suspilne eight. The lead's6August typo is resolved by Wednesday/publication date and local original."),
]

# Contested refers to the selected city peak, not merely to any earlier-day
# timing difference. Compatible lower bounds do not automatically create a dispute.
CONTESTED_CITIES = {"Kyiv", "Dnipro", "Odesa", "Chernivtsi"}
CITY_AUDIT_NOTES = {
    "Kyiv": "Police6000 versus organiser up-to15000 remains unresolved. Initial approximately1000 assembly is a separate time slice, not an alternative completed-march total.",
    "Kharkiv": "Peak450 on19July replaces the old first-day300 summary. Earlier first-day200/300 observations do not contest the later period peak.",
    "Dnipro": "Completed-march estimates approximately500 and400 remain distinct; the initial approximately100 assembly is not added. Latest documented action remains29August.",
    "Odesa": "The approximately1000 boundary estimate is supported by one relay report; retain the uncertainty flag rather than claiming independent corroboration.",
    "Ternopil": "Almost200 at20:30 on20July supersedes the old first-day100 peak; another report's >100 is compatible, not a conflicting upper bound.",
    "Poltava": "Peak130 on20July is now linked to its current-event sentence. Earlier first-day estimates are not competing estimates of this peak.",
    "Uzhhorod": "The unsupported200 headline is not a verified competing peak. The police approximately50 on16July remains selected; later snapshot and cumulative counts are distinguished.",
    "Rivne": "Fourth Estate's own approximately150 on24July replaces the former21July100 peak. Suspilne's >50 is a compatible lower bound.",
    "Chernivtsi": "Approximately150 at the31July march versus another local report's vague dozens remains a source discrepancy; timing does not resolve it.",
    "Kolomyia": "Only16July and20July are supported dated actions in this corpus. Later IFarticles were incorrectly indexed as Kolomyia via related-news blocks.",
    "Kremenchuk": "The24July several-dozen convention supports a normalized40 peak;31July has a separate >10 lower bound.",
    "Izmail": "The20July local report's approximately10 is newly recovered; the former unknown category is replaced.",
}

# Precise corrections to original publication rows. Preserve historical run.
PUBLICATION = {
    569: {"remove":True,"duplicate_of":566,"reason":"Full29Julyhromadske body describesKyiv only; no Lviv action or count. Wrong-city record duplicates validKyiv row."},
    477: {"category":"100–999","reason":"Current27JulyLviv article reports approximately150, not<100."},
    659: {"category":"unknown","quote_uk":"У центрі Києва та інших міст України 31 липня знову зібралися тисячі людей на акцію на підтримку Михайла Федорова.","reason":"Thousands is an aggregate across Kyiv and other cities; no city-only count is separated."},
    806: {"event_date":"2026-07-24","reason":"Retrospective report explicitly dates its own approximately150 observation to24July;25and26July observations are separate audit evidence."},
    234: {"event_date":"2026-07-16","quote_uk":"Вони розпочалися 16 липня","reason":"Kamianets-Podilskyi subsection explicitly dates the start to16July; four consecutive days are not used to invent an endpoint."},
    238: {"remove":True,"duplicate_of":232,"reason":"Local21JulyIFreport has no Kolomyia action; related-news furniture was misclassified."},
    451: {"remove":True,"duplicate_of":444,"reason":"Local27JulyIFreport has no Kolomyia action; related-news furniture was misclassified."},
    505: {"remove":True,"reason":"Local28JulyIFreport has no Kolomyia action; related-news furniture was misclassified."},
    552: {"remove":True,"duplicate_of":547,"reason":"Local29JulyIFreport has no Kolomyia action; related-news furniture was misclassified."},
    594: {"remove":True,"reason":"Local30JulyIFreport has no Kolomyia action; related-news furniture was misclassified."},
    631: {"remove":True,"duplicate_of":626,"reason":"Local31JulyIFreport has no Kolomyia action; related-news furniture was misclassified."},
    722: {"remove":True,"reason":"Local1AugustIFreport has no Kolomyia action; related-news furniture was misclassified."},
    747: {"remove":True,"duplicate_of":743,"reason":"Local2AugustIFreport has no Kolomyia action; related-news furniture was misclassified."},
    748: {"remove":True,"duplicate_of":744,"reason":"Local1AugustIFmarch report has no Kolomyia action; related-news furniture was misclassified."},
    763: {"remove":True,"duplicate_of":761,"reason":"Local3AugustIFreport has no Kolomyia action; related-news furniture was misclassified."},
    765: {"remove":True,"duplicate_of":764,"reason":"ConfirmedDW AMP samearticle/body/city/run;minute timestampdifference notdistinctpublication."},
    797: {"category":"unknown","quote_uk":"невідомо","reason":"No current5 Augustcount;31 July15000retrospectivecannotjustify<100."},
    702: {"published":"01.08","category":"unknown","quote_uk":"невідомо","reason":"Full31 JulyMykolaivreporthasnoheadcount;published1 August,URL2027notactualyear."},
    662: {"published":"01.08","reason":"Articlepublicationmetadata1 August;bodyexplicitlydatesKyivmarch31 July2026."},
    269: {"remove":True,"duplicate_of":267,"reason":"FullIF22 Julybody containsnoKolomyiaaction;wrongcityandcountassignment."},
    300: {"remove":True,"duplicate_of":297,"reason":"FullIF23 Julybody containsnoKolomyiaaction;wrongcityandcountassignment."},
    336: {"remove":True,"duplicate_of":328,"reason":"FullIF24 Julybody containsnoKolomyiaaction;wrongcityandcountassignment."},
    383: {"remove":True,"duplicate_of":379,"reason":"FullIF25 Julybody containsnoKolomyiaaction;wrongcityandcountassignment."},
    415: {"remove":True,"duplicate_of":410,"reason":"FullIF26 Julybody containsnoKolomyiaaction;wrongcityandcountassignment."},
    351: {"category":"unknown","quote_uk":"невідомо","reason":"Fullcurrent24 Julyreporthasnoheadcount;17 July>10000isretrospective, <100unsupported."},
    216: {"published":"19.07, 21:11","event_date":"2026-07-19","reason":"Articlemetadata andexplicitbody19 July;20 July isincorrect."},
    217: {"category":"100–999","quote_uk":"Близько 20:00 у центрі міста зібралися орієнтовно 130 людей.","reason":"CurrentPoltava130not<100;retrospectivefirst-day100excluded."},
    789: {"remove":True,"duplicate_of":788,"reason":"ConfirmedNV50630248 AMP equivalent samecity/run."},
    795: {"remove":True,"duplicate_of":794,"reason":"ConfirmedNV50630248 AMP equivalent samecity/run."},
    798: {"remove":True,"duplicate_of":808,"reason":"Uzhhorod-only report incorrectlyindexedKyiv."},
    799: {"remove":True,"duplicate_of":808,"reason":"Uzhhorod-only AMP duplicate incorrectlyindexedKyiv."},
    809: {"remove":True,"duplicate_of":808,"reason":"Confirmed samecity/run AMP duplicate."},
    805: {"remove":True,"duplicate_of":804,"reason":"Confirmed samecity/run AMP duplicate."},
    768: {"remove":True,"duplicate_of":773,"reason":"Uzhhorod-only local report, notKyiv; correct same-run row exists."},
    774: {"published":"04.08","reason":"Publication metadata4 August agrees with20th-day lead;3 August10:00 was unsupported."},
    775: {"published":"01.08, 14:33","reason":"Displayed publication date/time and metadata agree; baseline3 August is incorrect."},
    730: {"city":"Lviv","reason":"Local1 August Lviv report, not Kyiv."},
    731: {"remove":True,"duplicate_of":740,"reason":"Uzhhorod-only article misassigned toKyiv; correct same-run row exists."},
    736: {"city":"Kyiv","reason":"Full body only documentsKyiv31 July, notMykolaiv."},
    751: {"remove":True,"duplicate_of":754,"reason":"Lviv-only article misassigned toKyiv; correct same-run row exists."},
    752: {"remove":True,"duplicate_of":757,"reason":"Uzhhorod-only article misassigned toKyiv; correct same-run row exists."},
    755: {"provenance":"relay","reason":"Footer explicitly creditsodessa-life; author observations belong tooriginal publisher."},
    695: {"remove":True,"reason":"Full article describes Kyiv only; Lviv mentions are site footer/related news, not a protest observation."},
    653: {"remove":True,"duplicate_of":715,"reason":"Vinnytsia-only report misassigned to Kyiv; correct city row already exists in same run."},
    654: {"remove":True,"duplicate_of":691,"reason":"Lviv-only report misassigned to Kyiv; correct city row already exists in same run."},
    655: {"city":"Poltava","reason":"Local Poltava march, not Kyiv; preserve unique article/run."},
    656: {"remove":True,"duplicate_of":713,"reason":"Uzhhorod-only report misassigned to Kyiv; correct city row already exists in same run."},
    630: {"city":"Kyiv","category":"1000–4999","quote_uk":"У Києві тисячі людей вийшли на ходу за повернення Федорова","reason":"Khmelnytskyireferstomunitionsdetonation,notprotest;currentmarchsectionisKyiv."},
    598: {"city":"Ivano-Frankivsk","category":"<100","quote_uk":"прийшли орієнтовно 60 містян.","reason":"Local30JulyIFcount,notKyiv;deduplicateagainstcorrectsame-runcityrecord."},
    599: {"city":"Lviv","category":"100–999","quote_uk":"на проспекті Свободи зібралося близько 200 людей.","provenance":"police","reason":"Local30JulyLvivcount,notKyiv."},
    600: {"city":"Uzhhorod","category":"<100","quote_uk":"30 липня до мітингу долучилось близько 20 людей.","reason":"Local30JulyUzhhorodcount,notKyiv."},
    564: {"remove":True,"duplicate_of":574,"reason":"WrongKyivassignmentduplicatesPoltavasamearticle/run."},
    565: {"remove":True,"duplicate_of":580,"reason":"WrongKyivassignmentduplicatesUzhhorodsamearticle/run."},
    524: {"remove":True,"duplicate_of":523,"reason":"ConfirmedidenticalUA.newsarticlewith/uA/and/ua/languagepath,samecity/run."},
    537: {"remove":True,"reason":"UnrelatedsafetyreportaboutIvanFedorov,notMykhailoFedorovprotests."},
    511: {"city":"Lviv","category":"100–999","quote_uk":"На проспекті зібралося близько 200 людей.","reason":"LocalLviv28Julyreport,notKyiv."},
    512: {"city":"Sumy","reason":"LocalSumy28Julyaction,notKyiv."},
    513: {"remove":True,"duplicate_of":534,"reason":"WrongKyivassignmentduplicatescorrectUzhhorodsamearticle/run."},
    514: {"city":"Lviv","event_date":"2026-07-27","reason":"Lvivknifeincident27July,published28July;notKyiv."},
    520: {"city":"Lviv","event_date":"2026-07-27","category":"100–999","quote_uk":"У Львові, за даними поліції, на акцію вийшли близько 150 людей.","provenance":"police","reason":"Lviv27July150notKyiv28July."},
    458: {"city":"Rivne","category":"<100","quote_uk":"Понад 40 людей попри дощ зібралися 27 липня на Театральній площі у Рівному","reason":"LocalRivne27Julyreport,notKyiv."},
    459: {"remove":True,"duplicate_of":493,"reason":"WrongKyivassignment;existingcorrectUzhhorodarticleinthisrun."},
    457: {"city":"Lviv","category":"100–999","quote_uk":"За даними поліції, зібралося близько 150 людей.","provenance":"police","reason":"LocalLviv27Julycount,notKyiv;preserveuniquearticle/run."},
    346: {"city":"Lviv","reason":"LocalLvivreport,notKyiv; uniquearticlepreserved."},
    347: {"city":"Poltava","category":"<100","quote_uk":"зібралося майже вісім десятків людей.","reason":"LocalPoltavareport,notKyiv;current24Julyalmost80."},
    348: {"city":"Uzhhorod","reason":"LocalUzhhorodreport,notKyiv;eventdateconflictflaggedseparately."},
    390: {"city":"Lviv","category":"100–999","quote_uk":"За даними поліції, долучились близько 250 людей.","provenance":"police","reason":"LocalLvivpoliceestimate,notKyiv;25Julycorroboratedbyseparateroundup."},
    391: {"remove":True,"duplicate_of":402,"reason":"WrongKyivassignment;correctUzhhorodsamearticle/runalreadyexists."},
    392: {"city":"Cherkasy","category":"<100","quote_uk":"У Черкасах близько 80 людей вийшли на Соборну площу","reason":"LocalCherkasycurrentreport,notKyiv."},
    255: {"remove":True,"reason":"Full local Uzhhorod report contains no Mukachevo action; regional URL is not evidence."},
    277: {"remove":True,"reason":"Local Lviv action report incorrectly indexed forKyiv."},
    265: {"category":"<100","quote_uk":"менше ніж сотня дніпрян вийшла з гаслами на картонках","reason":"Current22Julystrictupperbound; no arbitrarynewpointestimate assigned."},
    242: {"city":"Lviv","reason":"Local Lviv report incorrectly assigned toKyiv; preserve unique article and historical run."},
    182: {"city":"Lviv", "reason": "Local Lviv action report, not Kyiv; preserve unique article and historical run."},
    183: {"remove": True, "reason": "Local Chernihiv action report, not Kyiv."},
    164: {"remove": True, "reason": "Unrelated Tysmenytsia traffic accident; no protest report."},
    8: {"quote_uk": "на мітинг зібралися сотні людей", "reason": "Remove editorial headline comparison from literal source quotation."},
    55: {"quote_uk": "невідомо", "provenance": "relay", "provenance_detail_uk": "Повідомлення читачів видання; тіло відновлено під час аудиту 3 Sep, числа немає.", "reason": "Recovered body attributes event to readers; prior JS-unavailable remark is not a quotation."},
    109: {"category": "online", "quote_uk": "Через безпекову ситуацію жителі Херсона долучаються до акції онлайн.", "reason": "Online-only modality is explicit in body; not an unknown street crowd."},
    113: {"quote_uk": "У Сумах акцію довелося скасувати через складну безпекову ситуацію.", "reason": "Preserve refuted historical status but remove analyst's refutation from source quotation."},
    144: {"quote_uk": "Окрім Києва та Львова, акції відбулися в Харкові, Одесі, Кам'янському, Дніпрі, Вінниці, Кременчуці, Івано-Франківську та інших містах України.", "reason": "Replace rewritten quotation with exact current-event sentence."},
    105: {"remove": True, "duplicate_of": 104, "reason": "Confirmed identical city/article/run; timestamps are same-run observations of the same updated article, not distinct publications."},
    13: {"quote_uk": "Протестувальники в Києві вщент заповнили площу і сквер біля театру ім. Франка.", "reason": "Keep non-numeric crowd description as literal excerpt; remove analyst prefix and time annotation from quotation."},
    31: {"provenance": "relay", "reason": "Nashe Misto body explicitly cites Suspilne Dnipro; not its own correspondent."},
    100: {"quote_uk": "У центрі Вінниці акція менш численна", "reason": "Non-numeric current-event description; preserve unknown category and literal wording."},
    738: {"event_date": "2026-07-31", "reason": "Opening body explicitly dates Rivne march to31July; 1August is publication date. Related-news half-hundred is not this march's count."},
    902: {"category": "unknown", "quote_uk": "невідомо", "reason": "The ~80 quotation belongs to Ivano-Frankivsk, not Zaporizhzhia. Independent SODA report confirms Zaporizhzhia action but gives no turnout count."},
    802: {"event_date": "2026-08-05", "reason": "Body explicitly says Wednesday 5 August; 6 August 00:24 is publication time."},
    901: {"category": "unknown", "quote_uk": "невідомо", "reason": "The quoted >50 belongs to Mykolaiv, not the article's Odesa subsection; retain Odesa occurrence without count."},
    810: {"event_date": "2026-08-05", "reason": "Body explicitly says the 22nd silent action occurred 5 August 2026; 6 August is publication date."},
    304: {"event_date": "2026-07-22", "provenance": "relay", "reason": "Published 23 July 00:04; seventh-day body and linked Suspilne original identify event as 22 July."},
    308: {"city":"Lviv", "reason": "Local Lviv article does not report a Kyiv action; correct city while preserving article/run."},
    419: {"city":"Lviv", "reason": "Local Lviv march article does not report a Kyiv action; correct city while preserving article/run."},
    420: {"remove": True, "reason": "Local Uzhhorod article does not report a Kyiv action; city misassignment."},
    422: {"city":"Khmelnytskyi", "reason": "Local Khmelnytskyi article does not report a Kyiv action; correct city while preserving article/run."},
    417: {"event_date": "2026-07-26", "reason": "Body explicitly says Sunday 26 July (11th protest day), not publication date 27 July."},
    460: {"category": "unknown", "quote_uk": "Наскільки я знаю, у Києві виходить кожен день від 4 до 6 тисяч.", "reason": "Undated interview generalization about daily turnout; not evidence of a particular city-day, and original <100 category contradicts its wording."},
    728: {"event_date": "2026-07-31", "reason": "Body explicitly says 31 July; 1 August is publication date."},
    732: {"event_date": "2026-07-31", "provenance": "relay", "provenance_detail_uk": "Переказ повідомлення організатора Козятинського.", "reason": "Body explicitly dates the march to Friday 31 July and attributes the description to Koziatynskyi."},
    733: {"category": "unknown", "quote_uk": "невідомо", "reason": "Original numeric quote consists of a related-news headline and page furniture, not this article's event body."},
    4: {"provenance": "relay", "reason": "Gazeta attributes the 1,400 count to Rubryka, not its own correspondent."},
    916: {"quote_uk": "Тисячі людей вийшли 18 липня на площу Франка в Києві.", "reason": "Replace rewritten sample-audit quotation with exact DW wording."},
    918: {"quote_uk": "Увечері 18 липня декілька сотень людей зібралися біля саду Шевченка.", "reason": "Replace rewritten sample-audit quotation with exact Nakypilo wording; retain normalization qualifier."},
}

# Source-level contextual review notes; flags are not automatic numeric evidence.
SOURCE_NOTES = {
    "b1a62b9fa1bcc6d6f364": "Reviewed full text: Kyiv 16 July, own Interfax reporter, approximately 2,000; age and participant descriptions are not counts.",
    "2fcb45588c0d4d0a94bb": "Reviewed city subsections: Kyiv 18 July 19:30 ~300 then 21:45 ~2,000; Kharkiv 20:00 police ~400. Keep observations separate.",
    "934a48a970c612c94a26": "Current Kyiv 20 July paragraph says hundreds. Later first-day retrospective paragraph must not supply a 20 July count.",
    "6ed9064bed7532f52009": "18 August current event <=30 at parliament; retrospective 14 August ~300 and 16 August <=1,500 are not 18 August turnout.",
}

# Literal fragments of already reviewed passages. Analyst annotations and
# quotation wrappers are not stored as if they were publisher wording.
QUOTE_REPAIRS = {
    436: "У Дніпрі на мітинг зібралися близько 80 людей.",
    465: "У Києві у сквері біля театру імені Івана Франка зібралися сотні людей.",
    477: "На ній зібралося близько 150 людей.",
    482: "До акції в Миколаєві долучилися близько 35 людей.",
    483: "а в Миколаєві – близько 35 учасників.",
    490: "у Рівному – близько 40",
    498: "У Дніпрі до протесту долучилися близько ста містян.",
    532: "У Рівному на Театральну площу вийшли приблизно 30 людей.",
    541: "У Дніпрі на акцію зібралися близько 80 людей.",
    555: "о 19:40 участь в акції взяли близько 10 людей.",
    590: "В Івано-Франківську на мітинг вийшли близько 60 містян",
    608: "В Ужгороді ж на мітинг прийшло 20 осіб.",
    617: "Загалом у Дніпрі на акції близько ста людей.",
    626: "Увечері 31 липня перед адмінбудівлею традиційно зібралися орієнтовно 120 учасників",
    658: "У Києві тисячі людей вийшли на мітинг на підтримку ексміністра оборони Михайла Федорова.",
    673: "У Києві тисячі людей вийшли на протестну ходу через відставку Федорова",
    674: "до якої долучилося кілька тисяч людей, як передають кореспонденти Радіо Свобода.",
    679: "У Києві в парку Шевченка близько тисячі людей зібралися на ходу",
    685: "до київської ходи 31 липня долучилися близько 6 тис. людей.",
    746: "Увечері першого серпня на площу перед адмінбудівлю прийшли орієнтовно 200 учасників",
    764: "Близько 200 мітингувальників зібрала у Києві у понеділок, 3 серпня, чергова акція протесту",
    806: "На Театральній площі у Рівному 24 липня на акцію, за нашими підрахунками, зібралося близько 150 людей.",
    917: "У Києві зібралося близько тисячі людей станом на 8-му годину вечора.",
    919: "зібралося близько 10 тисяч протестувальників.",
    920: "протестували близько 100−120 людей.",
    44: "16 липня в Івано-Франківську понад сотня людей зібралися на мирну акцію",
    67: "на акцію зібралось понад півсотні людей.",
    73: "У центрі Полтаві на протест вийшли близько сотні людей з «картонками»",
    114: 'Вранці 17 липня в Києві близько 200 учасників "картонкового протесту" знову зібралися на площі Івана Франка.',
    267: "Станом на початок акції зібралося приблизно 150 людей.",
    274: "У Києві, за даними Суспільне, зібралося близько 500 людей.",
    283: 'Журналістка "Суспільного" передає, що в Києві зібралося близько 500 людей.',
    328: "Участь у мітингу бере майже сотня людей.",
    343: "У Києві на протест зібралось близько 500 людей.",
    366: "Понад 50 людей зібралися, аби підтримати ексміністра оборони.",
    367: "Понад 50 людей зібралися, аби підтримати ексміністра оборони.",
    372: "Станом на 19:15 там було 40 осіб.",
    379: "На акцію зібралася понад сотня людей.",
    388: "на площу Франка в Києві прийшли вже не тисячі, як минулого тижня, а сотні людей.",
    18: "Щонайменше 300 людей зібралися на площі Свободи",
    19: "У саду Шевченка збираються десятки людей, переважно молодь",
    30: "близько 100 людей, проте їхня кількість збільшується",
    40: "Сотни одесситов собрались на Дерибасовской",
    41: "в Одесі десятки людей прийшли на акцію",
    45: "На мітинг прийшли десятки людей із плакатами",
    61: "Станом на 9:05 є біля 50 людей",
    63: "Всього зібралося біля 30 осіб, переважно молодих людей",
    64: "За інформацією Суспільного, на Соборній площі зібралися близько 30 містян",
    82: "зібралися 26 людей з плакатами",
    83: "Біля будівлі міської ради зібралися 26 людей",
}
for _row, _quote in QUOTE_REPAIRS.items():
    PUBLICATION.setdefault(_row, {}).update(quote_uk=_quote)
